name: ditonton_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: core
  movie:
    path: movie
  series:
    path: series
  about:
    path: about
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  dartz: ^0.10.0-nullsafety.2
  flutter_rating_bar: ^4.0.1
  get_it: ^7.2.0
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  equatable: ^2.0.5
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  build_runner: ^2.2.0
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - certificates/